name: Deploy App to Production

on:
  release:
    types:
      - published
  push:
    tags:
      - prod

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    name: Deploy App PR
    uses: ./.github/workflows/deploy-app.yml
    with:
      aws_cfn_stack_name: ls-ui-reactstarter-resources-prod
      aws_role_arn: ${{ vars.AWS_ROLE_ARN_PROD }}
      env: prod
    secrets:
      env_file: ${{ secrets.ENV_PROD }}
