name: Deploy Storybook

on:
  workflow_call:
    inputs:
      app_name:
        required: false
        type: string
        default: 'react-starter-storybook.leanstacks.net'
      aws_region:
        required: false
        type: string
        default: 'us-east-1'
      aws_role_arn:
        required: true
        type: string
      aws_cfn_stack_name:
        required: true
        type: string
      aws_cfn_template:
        required: false
        type: string
        default: '.aws/cfn/storybook.yml'
      env:
        required: false
        type: string
        default: 'dev'
    secrets:
      env_file:
        required: true

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Create Environment Configuration
        run: |
          echo "${{ secrets.env_file }}" > .env
          echo "VITE_BUILD_DATE=$(date +'%Y-%m-%d')" >> .env
          echo "VITE_BUILD_TIME=$(date +'%H:%M:%S%z')" >> .env
          echo "VITE_BUILD_TS=$(date +'%Y-%m-%dT%H:%M:%S%z')" >> .env
          echo "VITE_BUILD_COMMIT_SHA=${{ github.sha }}" >> .env
          echo "VITE_BUILD_ENV_CODE=${{ inputs.env }}" >> .env
          echo "VITE_BUILD_WORKFLOW_NAME=${{ github.workflow }}" >> .env
          echo "VITE_BUILD_WORKFLOW_RUN_NUMBER=${{ github.run_number }}" >> .env
          echo "VITE_BUILD_WORKFLOW_RUN_ATTEMPT=${{ github.run_attempt }}" >> .env

      - name: Build
        run: npm run build:storybook

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws_role_arn }}
          aws-region: ${{ inputs.aws_region }}

      - name: Deploy AWS CloudFormation Stack
        run: |-
          aws cloudformation deploy \
          --stack-name ${{ inputs.aws_cfn_stack_name }} \
          --template-file ${{ inputs.aws_cfn_template }} \
          --parameter-overrides EnvironmentCode=${{ inputs.env }} \
          --tags App=${{ inputs.app_name }} Env=${{ inputs.env }} OU=leanstacks Owner='Matthew Warman'

      - name: Get CloudFormation Stack Outputs
        id: cloudformation
        run: |-
          APP_BUCKET_NAME=$(
            aws cloudformation describe-stacks \
            --stack-name ${{ inputs.aws_cfn_stack_name }} \
            --query "Stacks[0].Outputs[?OutputKey=='AppBucketName'].OutputValue | [0]"
          )
          echo "APP_BUCKET_NAME=$APP_BUCKET_NAME" >> "$GITHUB_OUTPUT"

      - name: Deploy to AWS S3
        run: |
          aws s3 sync storybook-static s3://${{ steps.cloudformation.outputs.APP_BUCKET_NAME }} --delete
