name: Deploy Storybook to QA

on:
  push:
    branches:
      - release/*
    tags:
      - qa

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    name: Deploy SB QA
    uses: ./.github/workflows/deploy-storybook.yml
    with:
      aws_cfn_stack_name: ls-ui-reactstarter-storybook-resources-qa
      aws_role_arn: ${{ vars.AWS_ROLE_ARN_QA }}
      env: qa
    secrets:
      env_file: ${{ secrets.ENV_QA }}
