name: Deploy App to Development

on:
  push:
    branches:
      - main
    tags:
      - dev

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    name: Deploy App DV
    uses: ./.github/workflows/deploy-app.yml
    with:
      aws_cfn_stack_name: ls-ui-reactstarter-resources-dev
      aws_role_arn: ${{ vars.AWS_ROLE_ARN_DEV }}
      env: dev
    secrets:
      env_file: ${{ secrets.ENV_DEV }}
